// Auto-generated IOFramebuffer stub symbols
// These are empty placeholders for OpenCore vtable resolution

extern "C" __attribute__((visibility("default"))) void *__ZN13IOFramebuffer10gMetaClassE = 0;
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer10getVBLTimeEPyS0_() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer10hideCursorEv() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer10moveCursorEP8IOGPointi() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer10setDDCDataEij() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer10showCursorEP8IOGPointi() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer11flushCursorEv() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer11getDDCBlockEijjjPhPy() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer11readDDCDataEi() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer11setDDCClockEij() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer12connectFlagsEiiPj() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer12didTerminateEP9IOServicejPb() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer12doI2CRequestEjP14IOI2CBusTimingP12IOI2CRequest() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer12readDDCClockEi() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer12requestProbeEj() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer12setAttributeEjm() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer13getAppleSenseEiPjS0_S0_S0_() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer13newUserClientEP4taskPvjPP12IOUserClient() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer13serializeInfoEP11OSSerialize() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer13setGammaTableEjjjPv() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer13setGammaTableEjjjPvb() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer13setPowerStateEmP9IOService() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer13setPropertiesEP8OSObject() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer13willTerminateEP9IOServicej() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer14diagnoseReportEPvS0_S0_S0_() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer14setCursorImageEPv() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer14setCursorStateEiib() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer15enableDDCRasterEb() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer15getBoundingRectEPP9IOGBounds() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer15isConsoleDeviceEv() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer16enableControllerEv() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer16requestTerminateEP9IOServicej() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer17getAggressivenessEmPm() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer17setAggressivenessEmm() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer17setApertureEnableEij() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer17setInterruptStateEPvj() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer18convertCursorImageEPvP26IOHardwareCursorDescriptorP20IOHardwareCursorInfo() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer18setCLUTWithEntriesEP12IOColorEntryjjj() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer18setDetailedTimingsEP7OSArray() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer19unregisterInterruptEPv() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer20callPlatformFunctionEPK8OSSymbolbPvS3_S3_S3_() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer21getStartupDisplayModeEPiS0_() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer21powerStateDidChangeToEmmP9IOService() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer21setStartupDisplayModeEii() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer21setupForCurrentConfigEv() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer22powerStateWillChangeToEmmP9IOService() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer22validateDetailedTimingEPvy() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer23_RESERVEDIOFramebuffer3Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer23_RESERVEDIOFramebuffer4Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer23_RESERVEDIOFramebuffer5Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer23_RESERVEDIOFramebuffer6Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer23_RESERVEDIOFramebuffer7Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer23_RESERVEDIOFramebuffer8Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer23_RESERVEDIOFramebuffer9Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24_RESERVEDIOFramebuffer10Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24_RESERVEDIOFramebuffer11Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24_RESERVEDIOFramebuffer12Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24_RESERVEDIOFramebuffer13Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24_RESERVEDIOFramebuffer14Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24_RESERVEDIOFramebuffer15Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24_RESERVEDIOFramebuffer16Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24_RESERVEDIOFramebuffer17Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24_RESERVEDIOFramebuffer18Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24_RESERVEDIOFramebuffer19Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24_RESERVEDIOFramebuffer20Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24_RESERVEDIOFramebuffer21Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24_RESERVEDIOFramebuffer22Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24_RESERVEDIOFramebuffer23Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24_RESERVEDIOFramebuffer24Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24_RESERVEDIOFramebuffer25Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24_RESERVEDIOFramebuffer26Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24_RESERVEDIOFramebuffer27Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24_RESERVEDIOFramebuffer28Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24_RESERVEDIOFramebuffer29Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24_RESERVEDIOFramebuffer30Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24_RESERVEDIOFramebuffer31Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24getNotificationSemaphoreEjPP9semaphore() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer24registerForInterruptTypeEjPFvP8OSObjectPvES1_S2_PS2_() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer25setAttributeForConnectionEijm() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer4openEv() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer5closeEv() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer6attachEP9IOService() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer7messageEjP9IOServicePv() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer9setNumberEP12OSDictionaryPKcj() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebuffer9terminateEj() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebufferC2EPK11OSMetaClass() {}
extern "C" __attribute__((visibility("default"))) void __ZN13IOFramebufferD2Ev() {}
extern "C" __attribute__((visibility("default"))) void __ZNK13IOFramebuffer11getWorkLoopEv() {}
extern "C" __attribute__((visibility("default"))) void __ZTV13IOFramebuffer() {}
